backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  site_domain: vermillion-gingersnap-9f4345.netlify.app
  repo: 'piyushpaliwal/nextjs-ambit'
media_folder: 'public/img/articles'
public_folder: '/img/articles'
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/data/articles'
    create: true
    slug: '{{slug}}'
    preview_path: '/article/{{slug}}'
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
